### ISSUE TITLE
Warning with "geneura.bib"

### ISSUE THREAD

**Issue by iblancasa** [JJ/2016-ppsn-benchmark-ec#2]
When I run `make`

```
I couldn't open database file geneura.bib
---line 83 of file ea-languages.aux
```

We should fix it

**Comment by pacastillo** [comment]
It might be in the https://github.com/geneura/biblio

**Comment by JJ** [comment]
You have to add it to the BIBINPUTS

BIBINPUTS=.:./bib:../bib:/home/jmerelo/Papers/biblio

**Comment by iblancasa** [comment]
Last time I added it manually. I was thinking in add this in makefile:
if file is not present, use wget to download it

**Comment by JJ** [comment]
Good!

2016-02-10 18:55 GMT+01:00 Israel Blancas notifications@github.com:

> Last time I added it manually. I was thinking in add this in makefile:
> if file is not present, use wget to download it
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JJ/2016-ppsn-benchmark-ec/issues/2#issuecomment-182503058
> .

## 

JJ
